### ISSUE TITLE
Looking to have a server with a desktop for a application server such as Atlassian Jira

### ISSUE THREAD

**Issue by bonkerz1005** [fcaviggia/hardened-centos7-kickstart#18]
I have tried using your workstation version for this but i cant get past gnome login

**Comment by fcaviggia** [comment]
Have you tried using 'admin' as the user with the password you set during installation? I'm pretty sure I tested the login from GDM. Part of the README documentation here:

8. Create users:

	NOTE: The root user is locked now - use 'admin' user account with sudo instead of root.

**Comment by bonkerz1005** [comment]
I only see a prompt for a card for login. It wont let me type in a username

**Comment by fcaviggia** [comment]
I'll double check that, but it should allow either. I did make some changes for the last revision of SSG.  I can roll those back if it's a problem.

**Comment by bonkerz1005** [comment]
we have tried several time to use the workstation version on physical and virtual machines with the same issue

**Comment by fcaviggia** [comment]
Not a problem - I just revised the `/etc/pam.d/system-auth-local` configuration under `config/hardening/supplemental.sh ` and commented out the `pam_pkcs11.so` module on line 27. Let me know if that works for you.

**Comment by bonkerz1005** [comment]
Still get the prompt to insert the smart card

**Comment by fcaviggia** [comment]
I'll test again tonight.

**Comment by fcaviggia** [comment]
Okay, I fixed the issue with the last commit (https://github.com/fcaviggia/hardened-centos7-kickstart/commit/9060fb35598304f6f72347dfe1e42b3f45eabb89). Should work for you, please test and verify that the patch works for you.
