### ISSUE TITLE
CentOS 6+

### ISSUE THREAD

**Issue by jlamb85** [fcaviggia/hardened-centos7-kickstart#2]
This is not really an issue but why is there no hardened-centos7-kickstart?

**Comment by fcaviggia** [comment]
Do you mean hardened-centos6-kickstart? If that's the case - I haven't had time to develop it - I'm working on several different projects at this point.  CentOS 7 seemed like a good starting point with added SSG support.

**Comment by jlamb85** [comment]
Yes hardened-centos6-kickstart and that is true about the good starting point.  Thanks
