### ISSUE TITLE
a new version of scap-security-guid (0.1.35) exists

### ISSUE THREAD

**Issue by daswars** [fcaviggia/hardened-centos7-kickstart#20]
Hi,
a new version of scap-security-guid (0.1.35) exists
url: https://github.com/OpenSCAP/scap-security-guide/releases
url to rpm file -> https://copr-be.cloud.fedoraproject.org/results/openscapmaint/openscap-latest/epel-7-x86_64/00595351-scap-security-guide/

**Comment by fcaviggia** [comment]
Yep. Waiting until CentOS 7.4 (1708) is released. Will roll in with that update.

**Comment by fcaviggia** [comment]
I decided to sync with the version deployed with CentOS 7.4 (1708) - feedback came in that users would like to install the scap-workbench tool - if I go with the latest version, it prevents the installation of that. It is in sync with the RHEL 7.4 release as well.
