### ISSUE TITLE
Error when setting Installation Source

### ISSUE THREAD

**Issue by Ngpriddy** [fcaviggia/hardened-centos7-kickstart#21]
Hello,

I am receiving an error when trying to set an installation source. I used the CentOS-7 1708 ISO version for the hardened ISO. The pre-installation scripts execute fine, and after I set the root password, it starts executing the rest. It comes up with a text menu that has the set Language, Time, Network, and Kdump options. It is also asking for Instillation source, which I am using a DVD with a USB CD-ROM. It errors out when selecting this option, saying "Error setting up software source", which prevents me from continuing the installation. I think this might be an anaconda problem, but I'm not sure..

**Comment by fcaviggia** [comment]
Hi, I was planning on fixing everything for 7.4 (1708) this weekend - It came out this week and I didn't have time to integrate the changes that came with that release.

**Comment by fcaviggia** [comment]
You can also copy the ISO to a usb drive as well, but that might not work well in a SCIF.

**Comment by fcaviggia** [comment]
Updated for latest CentOS 7.4 (1708) updates - closing issue.
