### ISSUE TITLE
overt-release42.rpm md5sum not matching source

### ISSUE THREAD

**Issue by kasmtech** [fcaviggia/hardened-centos7-kickstart#35]
I'm trying to validate your scripts before utilizing it in our environment. I've downloaded all binaries included in the project directly from the source and comparing the hashes.

ovirt-release42.rpm does not match the hash or size of the same file downloaded from https://resources.ovirt.org/pub/yum-repo/. Would you be able to share where you got this rpm package from? Thank you!

**Comment by fcaviggia** [comment]
Updated to the latest Ovirt 4.3 release. Please test and reopen if still an issue.
