### ISSUE TITLE
Need help with stig for centos8 guinea Human?

### ISSUE THREAD

**Issue by symgryph** [fcaviggia/hardened-centos7-kickstart#39]
I would be willing to work with you on a STIG profile for centos 8 (non streaming update)

**Comment by fcaviggia** [comment]
Red Hat will typically develop the STIG in conjunction with DISA approval. I believe there also has to be a common criteria evaluation first as well.

https://www.niap-ccevs.org/Product/PCL.cfm
https://cyber.mil/
