### ISSUE TITLE
UEFI boot?

### ISSUE THREAD

**Issue by symgryph** [fcaviggia/hardened-centos7-kickstart#8]
I did try to use to create a hyperv type 2 vm (which only will boot efi) any special options to make work? Not a huge deal more of a question. The supplied iso didn't boot in efi mode, only in legacy mode.

Thomas

**Comment by symgryph** [comment]
I did find a script that claims to make a bootable iso out of centos 7, but am not sure how to merge the two. https://gist.github.com/vkanevska/fd624f708cde7d7c172a576b10bc6966

Thomas

**Comment by fcaviggia** [comment]
I did include some code for that:

https://github.com/fcaviggia/hardened-centos7-kickstart/blob/master/config/hardening/menu.py
lines 1026-27

I believe that you have to force the BIOS to say UEFI only boot - if you offer both options it will install legacy.

http://brainscraps.wikia.com/wiki/CentOS_7_Install_with_UEFI_Boot_and_Software_RAID1

**Comment by symgryph** [comment]
I actually didn't force the system to use EFI, I was trying to create type Ii hyper V  Image. The system simply did not see an EFI partition option even when bios turned off to efi boot only.  I will try to see if I can build on bare metal using EFI. I suspect that it is the stupid Microsoft problem.

Thomas J Munn

**Comment by symgryph** [comment]
Actually it doesn’t matter. Azure doesn’t support MS’s new version of hyperv (version 2). It also seems that you have to do lots to get it working. Sorry for the inconvenience.

Thomas

**Comment by symgryph** [comment]
Just as an fyi I did force my bios to boot 'only efi' (vmware) and the system wouldn't boot. I suspect there is a problem with the iso thing (you need to do this weird hybrid iso thing that has an efi partition on the root prior to the iso.

**Comment by fcaviggia** [comment]
Hey I found some information on EFI boot on the following blogs - I think that I need to make a hybrid EFI/Legacy DVD (2nd link) - I'll see what I can do to fix that. You might try modifying the genisoimage line on the createiso.sh script.

https://www.centos.org/forums/viewtopic.php?t=48639
https://www.centos.org/forums/viewtopic.php?t=55697

**Comment by symgryph** [comment]
I did try those, but the syntax was always wrong. Perhaps you will get better mileage.

Tomas

**Comment by fcaviggia** [comment]
Give the new version a shot - I tested it out in KVM with the EFI option.

https://github.com/fcaviggia/hardened-centos7-kickstart/commit/4fa54d6795c000286c4e47e318a925c05c422e60

**Comment by symgryph** [comment]
I did run the new version. EFI now boots but splash screen looks like this:

![hardenedefi 2017-04-07 16-27-51](https://cloud.githubusercontent.com/assets/4530798/24818593/344ece64-1baf-11e7-84f1-f9a2d3bfb926.png)

**Comment by symgryph** [comment]
I am using fusion using efi booted.

**Comment by symgryph** [comment]
Seems that this happens if you don't run the script from its current working directory with iso in root of the directory...I was running it the the arguments: /data/blah.centos.iso

If I run everything in cwd it works.

**Comment by symgryph** [comment]
I did run the install and then the system stops at partitioning. Looks like it runs the gui, tries to install, and errors out on partitions.

**Comment by fcaviggia** [comment]
Yeah, I'm doing some testing now - trying to integrate scap-security-guide-0.1.32 as well. Thanks for testing this - I don't have a ton of free time during the week.  I'll check out the EFI test here too.

**Comment by fcaviggia** [comment]
I think I'm making progress today - I should have some work posted soon.

**Comment by fcaviggia** [comment]
Okay, I've tested UEFI and normal installs with KVM. I think it's working correctly for both now.  Also, updated the to the latest version of the SSG.

**Comment by fcaviggia** [comment]
Let me know if the new version works for you - it's worked for me on KVM and VirtualBox with EFI boot.

**Comment by symgryph** [comment]
I ran this. EFI works great now. In fact, even BETTER than bios one with vmware since the 'continue' button was always off. Not so with EFI. I did notice that you probably need to include 'run from this directory' in order to get working images. I also have a 'dockerized' version of this if you want me to add the dockerfile.

**Comment by fcaviggia** [comment]
Cool, I've been working on a dockerized kickstart to use with Packer - I'd love to see a dockerfile version.
